name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-nifi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Azure credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

    - name: Extract credentials and set environment variables
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS_JSON }}" > credentials.json
        export ARM_CLIENT_ID=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["clientId"])')
        export ARM_CLIENT_SECRET=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["clientSecret"])')
        export ARM_TENANT_ID=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["tenantId"])')
        export ARM_SUBSCRIPTION_ID=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["subscriptionId"])')


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: ./terraform